apiVersion: apps/v1
kind: Deployment
metadata:
  name: creditcheckservice 
spec:
  selector:
    matchLabels:
      app: creditcheckservice
  template:
    metadata:
      labels:
        app: creditcheckservice
    spec:
      tolerations:
      nodeSelector:
      terminationGracePeriodSeconds: 5
      containers:
      - name: creditcheckservice
        image: docker.io/library/credit-check-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8888
        env:
        - name: SPLUNK_OTEL_AGENT
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://$(SPLUNK_OTEL_AGENT):4317"
        - name: OTEL_SERVICE_NAME
          value: "creditcheckservice:8888"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "deployment.environment=MB QEP"
        resources:
          requests:
            cpu: 110m
            memory: 90Mi
          limits:
            cpu: 130m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: creditcheckservice
spec:
  type: ClusterIP
  selector:
    app: creditcheckservice
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888